name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}  # Your EC2 public IP or DNS
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}  # Private key as GitHub secret
        script: |
          cd /home/ec2-user/my-react-app
          git pull origin main
          npm install
          npm run build
          sudo cp -r build/* /usr/share/nginx/html/
          sudo systemctl restart nginx
