name: Deploy React App to EC2

on:
  push:
    branches: [main] # deploy on main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Install dependencies & build
      - name: Build React (Vite) app
        run: |
          npm ci
          npm run build

      # 3️⃣ Copy build files to EC2
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/react-app"
          strip_components: 1

      # 4️⃣ Setup Nginx configuration and restart
      - name: Configure Nginx and restart
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure directory exists and has correct permissions
            sudo mkdir -p /var/www/react-app
            sudo chown -R www-data:www-data /var/www/react-app
            sudo chmod -R 755 /var/www/react-app
            
            # Create Nginx configuration if it doesn't exist
            if [ ! -f /etc/nginx/sites-available/react-app ]; then
              sudo tee /etc/nginx/sites-available/react-app > /dev/null <<EOF
            server {
                listen 80;
                server_name ${{ secrets.EC2_HOST }};
                
                root /var/www/react-app;
                index index.html;
                
                location / {
                    try_files \$uri \$uri/ /index.html;
                }
                
                location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
                    expires 1y;
                    add_header Cache-Control "public, immutable";
                }
            }
            EOF
              
              # Enable the site
              sudo ln -sf /etc/nginx/sites-available/react-app /etc/nginx/sites-enabled/
              sudo rm -f /etc/nginx/sites-enabled/default
            fi
            
            # Test and restart Nginx
            sudo nginx -t
            sudo systemctl restart nginx
